version: 2.0
jobs:
  build:
    steps:
      - checkout
      - run: npm install
      - run: npm run web-build  
      - run: echo '部署完毕'
workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build