name: website-builder

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build website
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: '14'
          check-latest: true
      - name: install
        env:
          NPM_CONFIG_PREFIX: '~/.npm-global'
        run: npm install -g dumi
      - name: build website
        run: dumi build
