name: website-builder

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build website
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: npm i -D dumi
      - name: build website
        run: ls
      - name: build website
        run: ls ~/.npm-global
