name: website-builder

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: actions/setup-node
          uses: actions/setup-node@v1.4.1
          with:
            node-version: '12'
            check-latest: true
      - run: sudo npm install -g dumi
      - name: build website
        run: dumi build
