name: website-builder

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: install deps
        run: npm install -g dumi

      - name: build website
        run: dumi build

