name: website-builder

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build website
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: npm i
      - name: build
        run: APP_ROOT=dumi ./node_modules/.bin/dumi build
      - name: update file and push to remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Update website"
          git push
